### ISSUE TITLE
Unable to compile Sass

### ISSUE THREAD

**Issue by dnguneratne** [welaika/wordless#212]
OS: Ubuntu 16.04

Steps:
1. Followed the `Getting started` and created a new theme.
2. `wordless compile` returns,
```bash
Problems compiling /var/www/html/wordpress_wordless/wp-content/themes/wordless/theme/assets/main.js to /var/www/html/wordpress_wordless/wp-content/themes/wordless/assets/main.js

WordlessCompileException: [0]: The path /opt/wordless/ruby doesn't seem to be an executable!

Output error:



PHP Notice:  Undefined variable: compiled_content in /var/www/html/wordpress_wordless/wp-content/plugins/wordless/wordless/wordless.php on line 146
Problems compiling /var/www/html/wordpress_wordless/wp-content/themes/wordless/theme/assets/javascripts/application.js.coffee to /var/www/html/wordpress_wordless/wp-content/themes/wordless/assets/javascripts/application.js

WordlessCompileException: [0]: The path /opt/wordless/ruby doesn't seem to be an executable!

Output error:



PHP Notice:  Undefined variable: compiled_content in /var/www/html/wordpress_wordless/wp-content/plugins/wordless/wordless/wordless.php on line 146
Problems compiling /var/www/html/wordpress_wordless/wp-content/themes/wordless/theme/assets/stylesheets/screen.sass to /var/www/html/wordpress_wordless/wp-content/themes/wordless/assets/stylesheets/screen.css

WordlessCompileException: [0]: The path /opt/wordless/compass doesn't seem to be an executable!

Output error:



PHP Notice:  Undefined variable: compiled_content in /var/www/html/wordpress_wordless/wp-content/plugins/wordless/wordless/wordless.php on line 146
```
`yarn run server` generates `screen.css`. I tried deleting `screen.css`, editing a Sass file and running `yarn run server` again. `screen.css` does not reflect the change made in the Sass file.

**Comment by pioneerskies** [comment]
Hi @dnguneratne ,

what I miss more is that you are about to try to compile using the `wordless compile` command. That is from another tool and moreover it works for themes written with Wordless <2.0.

So:

1. do not use the `wordless` command to compile a Wordless2 theme: it is compiled by webpack
2. be sure to be in you theme directory
3. launch `yarn run server` once and leave it alone. You don't need to relaunch the dev server in order to compile things
4. your browser will open
5. edit e.g. `screen.sass` file; never touch compiled assets generally speaking
6. you should see webpack output in your dev server STDOUT and all should be updated and the browser reloaded.

Here a recording of my dev server: https://asciinema.org/a/2mdddzPYWENVI2r0XmnF54JZt

**Comment by dnguneratne** [comment]
I used `wordless compile` since Sass didn't seem to be rendering. In hindsight Sass appears to be rendering and `screen.css` is generated. However, `style.css` is empty. Here's a gif what's happening.

![wordless_sass_compile](https://user-images.githubusercontent.com/8231763/32993222-e00deaa8-cd22-11e7-9e85-e86e898b5a34.gif)
The deleted `screen.css` gets regenerated, and it also has the newly added `color: red`,
```css
.page-wrapper header.site-header h1 {
  font-size: 25px;
  margin-bottom: 5px;
  font-weight: bold;
  color: red;
}
```

`default_hooks.php` contains,
```php
function enqueue_stylesheets() {
  wp_register_style("screen", stylesheet_url("screen"), false, false);
  wp_enqueue_style("screen");
}

add_action('wp_enqueue_scripts', 'enqueue_stylesheets');
```
Do I need to modify `webpack.config.js` to move styles from `screen.css` to `style.css`?

**Comment by pioneerskies** [comment]
Probably you can ignore what I wrote below the line: I've noticed a strange thing the last time I watched the GIF...I take the text as a reminder of my thoughts ;)

You have a `main.js` file inside `assets/`; the `main.js` file by default is in `theme/assets/`. Have you modified the default theme someway?

I've done a complete setup from 0, just to be sure, and I can't reproduce the issue... 🤔 
Here is a registration of my procedure with a just installed Wordless2 theme: https://cl.ly/0U0d172d3C3V

____________________________

Ok, you have already looked in a lot of right places in order to troubleshoot the issue :)

Now:

* there is no `style.css` anywhere, and it's ok for the default vanilla theme.
* The `enqueue_stylesheets` function looks just good and as it is by default.
* The `screen.css` is generated and in the place to be

From the build perspective no problem surfaces, as far as I can see.

Questions:

* have you modified `views/layouts/_head.html.pug`? Is there the `wp_head()` function called in the last line?
* in the generated HTML do you have

```html
<link rel="stylesheet" id="screen-css" href="//localhost:3000/wp-content/themes/wordless2_theme/assets/stylesheets/screen.css?ver=4.8" type="text/css" media="all">
```

?

My point is that if the CSS is compiled and in the right folder, then the problem should simply be in the theme not loading the CSS the right way...

**Comment by dnguneratne** [comment]
The way we create the project is a bit different.

1. Created a database using `phpMyAdmin`.
2. Copied a new `WordPress` install.
3. Went through the `WordPress` installer.
4. Used the commands in the `Getting started` section of the `Readme` to install `wordless` and create a new theme.

For me the default theme contains a `main.js` in `theme/assets`, and a `style.css` at root.
`theme/assets/main.js` contains,
```javascript
require('./javascripts/application.js.coffee');
require('./stylesheets/screen.sass');
```

![newproject](https://user-images.githubusercontent.com/8231763/32997257-35f60d32-cd5b-11e7-80c3-555bbb0785b8.png)

`theme/views/layouts/_head.html.pug` contains,
`- wp_head()`

The generated HTML contains,
```html
<link rel='stylesheet' id='screen-css'  href='//localhost:3000/wordpress_test/wp-content/themes/mybrandnewtheme/assets/stylesheets/screen.css?ver=4.9' type='text/css' media='all' />
```
![pgsource](https://user-images.githubusercontent.com/8231763/32997350-f54313aa-cd5c-11e7-94bd-39961b6b0363.png)

I tried manually deleting `style.css` and running `yarn run server`, but the results are the same.

This is the default `webpack` config file I have (except for the `BrowserSyncPlugin` setup),
```javascript
var path = require('path');

var srcDir = path.resolve(__dirname, 'theme/assets');
var dstDir = path.resolve(__dirname, 'assets');
var javascriptsDstPath = path.join(dstDir, '/javascripts');
var stylesheetsDstPath = path.join(dstDir, '/stylesheets');

var BrowserSyncPlugin = require('browser-sync-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  entry: path.join(srcDir, '/main.js'),

  output: {
    filename: 'application.js',
    path: javascriptsDstPath,
  },

  devtool: 'source-map',

  module: {
    loaders: [
      {
        test: /\.coffee$/,
        loader: 'coffee-loader',
      },
      { test: /\.s(a|c)ss$/, loader: ExtractTextPlugin.extract('css-loader?sourceMap!resolve-url-loader!sass-loader?sourceMap') },
      { test: /\.css$/, loaders: ['style-loader', 'css-loader', 'resolve-url-loader'] },
      {
        test: /\.(jpe?g|png|gif|svg)$/i,
        loaders: [
            'file-loader?hash=sha512&digest=hex&name=../images/[hash].[ext]',
            'image-webpack-loader?optimizationLevel=7&interlaced=false'
        ]
      }
    ],
  },
```

**Comment by pioneerskies** [comment]
In the `plugins: []` in your `webpack.config.json` there are both browsersync and extracttextplugin?

```
  plugins: [
    new BrowserSyncPlugin({
      host: '127.0.0.1',
      port: 3000,
      proxy: {
        target: 'http://127.0.0.1:8080',
      },
    }),
    new ExtractTextPlugin('../stylesheets/screen.css'),
  ]
```

But let me get a point: if you open in chrome http://localhost:3000/wordpress_test/wp-content/themes/mybrandnewtheme/assets/stylesheets/screen.css, can you read your css file there?  Because...well...if there's a `<link>` sourcing the css in the `<head>` section, if the file has expected contents, then...well...I'm feeling lost about where the problem should be from a good old HTML point of view... 😖

**Comment by dnguneratne** [comment]
The browsersync and extracttextplugin are there. I just didn't post it.
When I go to `http://localhost:3000/wordpress_test/wp-content/themes/mybrandnewtheme/assets/stylesheets/screen.css` I get,

![html_screen css](https://user-images.githubusercontent.com/8231763/33019679-5e200f60-cdc9-11e7-8d52-e87b4d79a7dd.png)

What's interesting is the `WordlessCompileException: [0]` error is the same error I got when I ran `wordless compile` as shown in my first post, except this time I didn't run `wordless compile` and the browser is showing it.

**Comment by pioneerskies** [comment]
OK; I'm sorry if the conversation is getting long, but probably I'm getting a clue.

My hypothesis is that for some reasons you are entering the fallback process using the ruby compile  infreastructure (Wordless was based on some ruby gems until version 0.5.x). It's possible that the bug arises when we have no ruby setup present in the dev environment. I'll try to reproduce.

Stay tuned and thanks a lot for your patience and commitment

**Comment by pioneerskies** [comment]
I can reproduce your scenario when:

* I run `yarn run serve`
* I delete `screen.css`
* I reload the browser

And this is expected behaviour: if no `screen.css` is present, we get back to the old ruby system, which generates the reported `WordlessCompileException`.

But if I stop and reload the dev server again or if I update SASS, then `screen.css` is recompiled and then the front page newly loads successfully. As far as i can troubleshoot, the software is behaving correctly.

The - probably - last thing I'd check are folder permissions: if PHP can't correctly read the `screen.css` file, then it try to invoke the ruby compile chain. We assume that as far as webpack is running, `screen.css` will be present.

Does all of your project's folder have 775 and all of your files have 664?

**Comment by pioneerskies** [comment]
@dnguneratne ,

would you like to try to `wp rewrite structure '%postname%'` and give it a try?

**Comment by pioneerskies** [comment]
@dnguneratne I've done a test without using my WordPress installation utility, and I can confirm it works even w/o the rewrite structure. Here's my command history in reverse order (from bottom to top)

```
yarn run server
yarn
cd wp-content/themes/wpplain/
wp plugin activate wordless
wp wordless theme create wpplain
wp plugin install wordless
wp core install --url=http://localhost:8080 --title=wpplain --admin_user=admin --admin_email=alessandro.fazzi@welaika.com
mysql -u root         <-- Here I've created the database
wp config create --dbname=wpplain --dbuser=root
wp config create
cd wpplain/
wp core download --path=wpplain
```

which bringed to https://cl.ly/0F2h3B1A3T3B

What to do? Any news from your side?

**Comment by Migg88** [comment]
I have the same issue ¿did u fix it? any solution?

**Comment by Migg88** [comment]
Well, i followed  the steps that you mention before and now it's working fine. Idk why, but now all it's running in the right way. Thanks for your attention! 

> @dnguneratne I've done a test without using my WordPress installation utility, and I can confirm it works even w/o the rewrite structure. Here's my command history in reverse order (from bottom to top)
> 
> ```
> yarn run server
> yarn
> cd wp-content/themes/wpplain/
> wp wordless theme create wpplain
> wp plugin install --activate wordless  <-- some warnings here complaining about no wordless theme present
> wp core install --url=http://localhost:8080 --title=wpplain --admin_user=admin --admin_email=alessandro.fazzi@welaika.com
> mysql -u root         <-- Here I've created the database
> wp config create --dbname=wpplain --dbuser=root
> wp config create
> cd wpplain/
> wp core download --path=wpplain
> ```
> which bringed to https://cl.ly/0F2h3B1A3T3B
> 
> What to do? Any news from your side?

**Comment by pioneerskies** [comment]
Oh! Well ... nice! 😄 Feel free to contact us if you need further help and don't miss the shiny new documentation @ https://wordless.readthedocs.io/ 😉
