### ISSUE TITLE
file_put_contents Permission Denied

### ISSUE THREAD

**Issue by vjsingh** [welaika/wordless#215]
EDIT: Fixed, see below

Hey all,

I recently got a new laptop, and am attempting to get my wordpress site up and running locally. I copied over the database from production.

Note: I know I'm working with an old version of Wordless (0.5.5). I'd like to upgrade, but I'm working with a production site, so first things first I'd like to get this sorted out.

I did manage to get the site up and running. However, after making a change and then running "wordless compile," I'm now seeing the below errors whenever I try to open the site (working dir replaced with "DIR").

******
Warning: file_put_contents(DIR/wp-content/themes/wordless_3/tmp/b4d97ae253a32a6f010a371e73478fa2.php): failed to open stream: Permission denied in DIR/wp-content/plugins/wordless/vendor/phamlp/haml/HamlParser.php on line 412

Warning: include(): Filename cannot be empty in DIR/wp-content/plugins/wordless/wordless/helpers/render_helper.php on line 69

Warning: include(): Failed opening '' for inclusion (include_path='.:/Applications/XAMPP/xamppfiles/lib/php') in DIR/wp-content/plugins/wordless/wordless/helpers/render_helper.php on line 69
******

I would really appreciate any help, totally stuck here. Thank you

Edit: I printed out the file causing the error. HamlParser.php line 413 says: "$return = (file_put_contents($outputFile, $this->haml2PHP($sourceFile))"

$sourceFile here is "DIR/wp-content/themes/wordless_3/theme/views/posts/home.haml". 

That file was owned by root (not sure why). I've chowned the file, but am still getting the same error, even after running "wordless compile" again. I suppose one question is who is running the php file? Presumably XAMPP?

**Comment by vjsingh** [comment]
Wooooohoooooooooo I fixed it!!

I had to rm everything in "<theme>/tmp/" and then the problem went away.

**Comment by pioneerskies** [comment]
Dear @vjsingh ,

I'm really glad you sorted it out. In the new version of wordless I'd like to add a wp-cli command to rapidly blank the tmp folder, 'cos sometimes could be useful and moreover is a classic troubleshooting pattern.

Just saying: when we updated Wordless to its new shiny JS-based version, we spent a lot of energy trying to make it completely backward compatible. Actually Wordless2 plugin's code is bigger then the 0.5.5's one because it continue to fully support HAML and ruby-based assets compiling.

I've personally updated Wordless to the last version - which is out of beta from the end of the past year - on more than 10 production sites at it just worked. This is just for your information. `wordless-gem` has a reminder for who is using [Wordless <2](https://github.com/welaika/wordless_gem#wordless--2-) ... thus, you are not alone :)

Anyway I'm looking forward to hear from your next site built with Wordless2 and its new compilation stack ;)

Have a nice day.

P.S.: closing, since you also posted your own solution ;)

**Comment by vjsingh** [comment]
Thank you! This is an old site, and honestly PHP and Wordpress terrify me since I don't know much about them and have spent far too much time debugging problems with them. We are still on PHP 5.6.32 =) 

Because of that, I will likely not upgrade to the new Wordless anytime soon, but if I start a new project I'll keep it in mind, because it does look good. Thanks again for all your help
