### ISSUE TITLE
Allow expressionLanguage to be set by the theme

### ISSUE THREAD

**Issue by juankk** [welaika/wordless#237]
The Theme should have a filter to set the expressionLanguage in when rendering pug templates. 

https://github.com/welaika/wordless/blob/06b9945bbf08810d1e7b3d124556fce278023cde/wordless/helpers/pug/wordless_pug_options.php#L8

We are planning on connecting out templates with [Story Book](https://storybook.js.org). A simple filter that the theme can override the configuration of PUG will do. 

Here is the patch as I cannot commit to this repo:

[wordless_pug_expression_language_override_patch.diff.txt](https://github.com/welaika/wordless/files/3279413/wordless_pug_expression_language_override_patch.diff.txt)

**Comment by pioneerskies** [comment]
Hey hey there :)

First thing first: you can't commit on the repo, but you should be able to do a pull request from your own fork.

Anyway this does not matter so much, since your patch is easy and tiny. Moreover I found it smart and useful, so I'm really prone to implement it.

Second thing second: our CI cannot push the plugin on wordpress.org repo since our heroes does not support plugins with contemporary PHP syntax and we have no intention to downgrade our vendor dependencies. So: I'd be glad to proceed implementing the feature, but you'll have to install the plugin through github repo

```
wp plugin install https://github.com/welaika/wordless/archive/master.zip
```

are you aware of this? :)

Thanks for your really really appreciated and clean contribution

**Comment by pioneerskies** [comment]
ref #220

**Comment by juankk** [comment]
Agree I should have forked it and create a PR for it but it was such a small change .

Thanks I am aware of not working on wordpress.com and i have to install it using cli. Can you expand a bit more on "contemporary PHP syntax"?

My plan is to run this plugin within WordPress VIP Go and so far it is doing to pretty good.

**Comment by pioneerskies** [comment]
Unfortunately PHP7 stands for PHP7.0.

o.O Ouch

**Comment by pioneerskies** [comment]
@juankk we're out: https://github.com/welaika/wordless/releases/tag/2.7.0

Tell me if it works for you and close the issue if it actually is, please.

Thanks again

**Comment by juankk** [comment]
Thanks just tested it and working as expected. Thanks again
