### ISSUE TITLE
More flexible please

### ISSUE THREAD

**Issue by Alexufo** [welaika/wordless#239]
Hard coded urls in theme it is  not good. I want css instead 'Stylesheets'. I prefer src with scss,js, folders and etc. 

Thanks for good plugin.

**Comment by pioneerskies** [comment]
Hello @Alexufo ; I'm on the way of a new release and I'm considering your notes.

* First thing first: thanks for your feedback
* i'm removing `assets` and `theme` directory (they were there for backward compatibility reason, but it's time to move forward) opting for `src`/`dist` (`views` will go up one level)
* i'll leave `strylesheets` because one could use sass, sugarSS, you-name-it-SS and I like to remain agnostic
* I can't get what hard-coded URLs you've found :) But hey: if they are in the theme keep in mind that the theme is there just to simplify the initial scaffold/bootstrap, not to be used as a real theme. BTW if you'll mind to point theme out I will remove those in the next release.

I'll quote this ticket inside the PR for the new release, so you'll be updated.

Thanks again.

Cheers

**Comment by pioneerskies** [comment]
@Alexufo https://github.com/welaika/wordless/releases/tag/3.0.0 is out FYI :)

Hope you'll take a look for the next project ;)
